### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by truegold** [miyako/4d-component-classic-query-editor#2]
Hi Miyako

Vance at 4D TS asked me to tell you about a problem we've identified while debugging some windows issues.

How I discovered and tested:

4D Server 15.2 (on a Macintosh)
4D Windows 15.2 connected via Windows 10 or Windows 7.

Running a source or compiled version of classic-query-editor. As soon as the On Startup routine is called an error message appears. Here's the contents of the dialog:

Runtime Error

Error

The specified module could not be found.

Process 1 Application process
1010 - The specified module could not be found.

After many hours of debugging we discovered that if you File->Open->Remote Database and login in you get the error. If you close 4D and reopen it you get the error.  But if you disconnect the database (close database for example) and reopen it without closing 4D, then the error doesn't show again.

Anyway, I need to resolve as this is affecting my windows clients and I cannot figure out what's missing

Appreciate, as always,
John...

**Comment by miyako** [comment]
you need to change the database language to English

**Comment by miyako** [comment]
see also http://forums.4d.fr/Post/FR/18441594/1/18441595#18441595

**Comment by truegold** [comment]
Hi Miyako,

Thank you.

I must say it never occurred to look for resolving this issue in a topic named "Curl Plugin / module could not be found" in the "The 4D v15 corner". I have used this for months and my clients love it. But only recently, I'm guessing, have the clients opned in windows.

Anyways, I'll give it a try and get back with you to confirm it works.

Thanks,
John...

**Comment by truegold** [comment]
Hi Miyako,

So I reviewed my code and it does seem to be properly seeding the routine. The language is "en". Here's the routine:

QRY_CLASSIC(->[TABLE])

C_POINTER($1;$table_ptr)

If (Count parameters>0)

C_OBJECT($params)
$table_ptr:=$1

OB SET($params;"tableNumber";Table($table_ptr);"repeat";False;"developer";False;"language";"en";"selection";False)

CLASSIC_QUERY ($params)

end if

Any other ideas? Please understand it's not even at the point of initializing this component. As soon as On Startup is called it brings up the error.

So whatever is supposed to be must've have already been checked by 4D internally. 

Unless I have misunderstood what the "curl" thread said?

Thanks,
John...

**Comment by miyako** [comment]
I meant database settings

**Comment by truegold** [comment]
Hi Miyako,

Ahhhhhhh!

OK, I'll let you know if that fixes things.

Appreciate,
John...
