### ISSUE TITLE
Saving the Tablelists

### ISSUE THREAD

**Issue by MartinGaebler** [miyako/4d-component-classic-query-editor#3]
Hi Miyako,

do you see any chance of saving the tablelists for example in a database? I tried that through List to Blob and saved it in a new table but you will loose the little type-pictures at the front. I want to create the lists once and use it for all the clients. It takes far too long to create the lists at every startup and needs too much space. The list of the first table is about 36MB as a blob.

Greetings
Martin

**Comment by miyako** [comment]
Hi, I've added a depth option, which limits the number of relation to 3 (max 9). 

Hopefully that solves the speed issue without the need for more aggressive caching.

**Comment by MartinGaebler** [comment]
Thanks for your great work.
The first table is now only 2,5MB as a blob and now i can use your component.

For your next version you could add a "is table number valid" in your method "Cache_CREATE_LIST". That would invoid some errors.

**Comment by miyako** [comment]
Thanks!

I think the root causes are in the methods called from Cache_CREATE_LIST;

Table_Create_list_all
Table_Create_list_master
Table_Create_list

I've modified the methods accordingly
