### ISSUE TITLE
Editor update

### ISSUE THREAD

**Issue by xbeben** [miyako/4d-component-classic-query-editor#4]
Hi Miyako,

Thanks for this very useful component.
Just a small question because I can not change a value in a loaded query.
I may have forgotten to send a parameter because by clicking on a line in the top frame, it is not possible to change the value.
Thank you.

**Comment by miyako** [comment]
Hi, you just need to select the line and type in the field at the bottom of the editor. 
The list itself is not editable.

**Comment by xbeben** [comment]
Hello,
I misspoke !
After loading a .4df file into the editor, I can not change the value of one of the lines.

**Comment by miyako** [comment]
I am sorry I do not understand your problem.

**Comment by xbeben** [comment]
And with a screenshot ?
![queryexemple_load](https://cloud.githubusercontent.com/assets/26168941/23648556/8346778a-031b-11e7-81be-46402211ebca.png)

**Comment by miyako** [comment]
In you screenshot you do not have the focus in the "Valeur" area; the focus is on the field list.

**Comment by xbeben** [comment]
Excuse me for being insistent and thank you in advance for your answers.
After clicking [2] on any line (top area), the field and comparison above are not reloaded.
I must to re-select the field and the comparison before modifying the value.
If I click on a line on the top and directly modify the modify the value in "Valeur" area, the last field and comparison memorized replace the current top line.
Thank you.

**Comment by miyako** [comment]
The current behaviour was supposed to be an imitation of the classic editor, I think, but maybe I was wrong. Anyway, I've made a lot of changes to make the UI a bit more friendly in today's update.

I hope you like it.

**Comment by xbeben** [comment]
It's awesome, thank you.
Exactly what I needed, the editor approaches perfection :)

I continue to test it.
