### ISSUE TITLE
After loading .4df file

### ISSUE THREAD

**Issue by xbeben** [miyako/4d-component-classic-query-editor#5]
Hi,
After new tests, I have an anomaly and a question.

When loading the .4df file (v13) I only have 2 lines out of 4 which are taken over.
Is it normal "values" ​​are not taken when loading the .4df file?

Thank you.

**Comment by miyako** [comment]
I can look into it if you send me the ``.4df``

**Comment by xbeben** [comment]
.4df file (v13) with 4 lines and values date.

[exemple.4df.zip](https://github.com/miyako/4d-component-classic-query-editor/files/854143/exemple.4df.zip)

**Comment by miyako** [comment]
it should be better now; the problem was that some fields were using 7 or maybe 8 bits out of 16, so I should have cleared the irrelevant bits after BLOB to integer.

**Comment by xbeben** [comment]
Yes, it is better. Very good job :)
In "Format_Date" you defined the day position, the month position and the year position but you do not use it to create the final date!

**Comment by miyako** [comment]
is that a request or statement? do I need to change something?

**Comment by miyako** [comment]
OK, I think I understand what you mean; I thought the ``Date`` function would take care of that, but maybe I was wrong. please check the latest version.

**Comment by xbeben** [comment]
Thank you, it's great.
